remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: AbLECPS
description: Assurance-based Learning Enabled Cyber Physical Systems
logo: /imgs/AbLECPS.png
email: alc-team@vanderbilt.edu
color-scheme: light

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/AbLECPS/alc

navigation:
  - name: ALC-Toolchain
    link: ./
    sublist:
      - name: UUV Example
        link: ./uuv.html
      - name: LECs & AMs
        link: ./lecs_ams.html
      - name: UUV Challenge Problems
        link: ./activities.html
      - name: Challenge Problem 1
        link: ./activities_cp1.html  
      - name: Challenge Problem 2
        link: ./activities_cp2.html
      - name: Challenge Problem 4
        link: ./activities_cp4.html
      - name: Results & post process
        link: ./results.html
